server:
  port: 8080
# spring-data 配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourheadline?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone = Asia/Shanghai
    username: root
    password: gmcq19990118-.-
