server:
  port: 8080
# spring-data 配置
spring:
  datasource:
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourheadline?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone = Asia/Shanghai
    username: root
    password: mysql

  hikari:
    maximum-pool-size: 20
    spring.datasource.hikari.minimum-idle: 5
    # JPA 相关配置
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    spring.jpa.show-sql: true
    
    
    dd

